### ISSUE TITLE
doesn't work on Android

### ISSUE THREAD

**Issue by teo1978** [wouterverweirder/AIR-Mobile-UDP-Extension#1] opened 2012-04-02 18:11 UTC
The UDPServer extension simply does not work on Android, at least for RECEIVING packets.

I've tried the code in your demo and sent packets from another computer in the same network.
The DatagramSocketDataEvent just never gets fired.

**Comment by teo1978** [comment] 2012-04-02 18:41
Hey actually it does work if the packets are sent to the specific IP of the device, but it doesn't work for BROADCAST  packets, i.e., packets sent to the broadcast address of the local network are not received.

Is there a workaround to make it work with boradcast packets too?

**Comment by wouterverweirder** [comment] 2012-07-26 15:02
AIR on desktop can only receive broadcast packets, not send broadcast packets.

**Comment by teo1978** [comment] 2012-07-26 15:45
I'm not sure that's true, but even if it was, so what? The bug I'm describing is that _this native extension_ is not _receiving_ broadcast packets. It has nothing to do with _AIR for Desktop_ not _sending_ broadcast packets.

**Comment by teo1978** [comment] 2012-07-26 15:56
Oh maybe I understand. You thought I was testing sending broadcast packets from an Adobe AIR application for Desktop, so you deduced it was the sending that was failing. No, I tested by sending broadcast packets from another program (now I don't remember whether it was Processing or Pd or both), and I verified that yet another program on the same network on a different machine was receiving them.

**Comment by wouterverweirder** [comment] 2012-09-06 09:33
duplicate of https://github.com/wouterverweirder/AIR-Mobile-UDP-Extension/issues/4

**Closed as completed by wouterverweirder** 2012-09-06 09:33 UTC
